name: Deploy to docker hub

on:
   push:
     branches:
      - master
     tags:
       - '*.*.*'

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Frontend
        if: success()
        run: cd frontend && docker build -t jzlotek/bcfrontend:${IMAGE_TAG} . -f ./Dockerfile

      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push jzlotek/bcfrontend:${IMAGE_TAG}


  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        if: success()
        run: cd backend && docker build -t jzlotek/bcbackend:${IMAGE_TAG} . -f ./Dockerfile
      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push jzlotek/bcbackend:${IMAGE_TAG}
  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@master
        name: Setup Repo
      - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        name: Get Helm
      - name: Get Repo
        run: |
          helm repo add jzlotek https://jzlotek.github.io/helm-charts
          helm repo update
      - name: Deploy
        run: |
          helm upgrade --install bcbackend --set image.tag=${IMAGE_TAG} --values backend/helm/values.yaml --namespace bc
          helm upgrade --install bcfrontend --set image.tag=${IMAGE_TAG} --values frontend/helm/values.yaml --namespace bc
