name: Deploy to docker hub

on:
   push:
     branches:
      - master
     tags:
       - '*.*.*'

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Frontend
        if: success()
        run: cd frontend && docker build -t bcfrontend:${IMAGE_TAG} . -f ./Dockerfile

      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push bcfrontend:${IMAGE_TAG}

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        if: success()
        run: cd backend && docker build -t bcbackend:${IMAGE_TAG} . -f ./Dockerfile
      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push bcbackend:${IMAGE_TAG}
